apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-minikube-v1
  namespace: default
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hello-minikube
  targetCPUUtilizationPercentage: 90
